### ISSUE TITLE
[yml/spaced-comment] Rule detected problems

### ISSUE THREAD

**Issue by joseh29** [ota-meshi/eslint-plugin-yml#161]
The rule defined in here: https://github.com/ota-meshi/eslint-plugin-yml/blob/master/src/rules/spaced-comment.ts
Has at least, IMO one regex problem.

This is considered an error:
```
## comment
```
Because it states it should be:
```
# # comment
```

From what I understand from this rule, it should only validate if there are spaces in between the comment "char" and the actual string itself. I understand if everything after the first `#` is interpreted as `the comment itself`, but shouldn't the same char (`#`) of making comments be supported? 🤔

I'm thinking of comments such as:
```
##########
# HEADING #
##########
```
That will break because of this rule. (to whom it might concern, in my case the ## is fine 😆)

**Comment by ota-meshi** [comment]
You can set the rule options to accept your favorite comment style.
https://ota-meshi.github.io/eslint-plugin-yml/rules/spaced-comment.html#options

https://ota-meshi.github.io/eslint-plugin-yml/playground/#eJxdjLEKwyAQQH/lOIcslu5ugYa2S3+gZhBzQ0DP4FnaIP577FTo2x4PXkWfFkKDCkjCygX2GM6yOU/LyacYiYuBJ+WcsgYX3m4XDRXo42kra2LpdVDDDA1my5bVjy5wm8bL/XEF9Ve6Tt+nZdSYX4EETW3tAOBPK9M=

https://ota-meshi.github.io/eslint-plugin-yml/playground/#eJwtyzsKwzAQRdGtPEaFG4X06r0K24WQpgjWx8w4BCG0d8ch5eVyOoUamRwZsKZXOdFyeurhA8dHqDlzOR0WFqli4dPHN7XoyF52Fv2uyUwbBra1rMUY/M2v5luRJXknVnJ9jAtI6iYJ
