### ISSUE TITLE
Enforce yml file extension

### ISSUE THREAD

**Issue by psirenny** [ota-meshi/eslint-plugin-yml#173]
Projects accumulate varying file extensions (`.yml` and `.yaml`) based on the preferences or whims of developers. It would be great to enforce consistent usage!

For example:

```json
"rules": {
  "yml/file-extension": ["error", "always", {
    "prefer": ".yaml"
  }]
}
```

**Comment by ota-meshi** [comment]
Thank you for suggesting the rule.
That rule sounds good to me!

**Comment by psirenny** [comment]
Awesome, thanks!
