### ISSUE TITLE
Ability to ignore some filenames with `yml/file-extension`

### ISSUE THREAD

**Issue by MorevM** [ota-meshi/eslint-plugin-yml#190]
Hi! 
First of all, thank you for all your work, not only this plugin - I use your solutions every day and work becomes much easier with it :)

I noticed the new rule `yml/file-extension` doesn't have an option to skip some filenames.
I personally prefer full `.yaml` extension, but some environments doesn't provide a way to use it. 

For example, [`dependabot.yml`](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file) is forced to have `.yml` extension - it's just doesn't work if you rename it to use `.yaml`. 
(Actually I checked this like a year ago, but I didn't see any updates on this)

Also I never saw `.gitlab-ci.yml` file written with full extension - maybe there is the same limitation.

I use the shared ESLint configuration across all projects and it seems a bit annoying to reconfigure the rule per-project again and again :)
So, can we extend this rule to skip some names?

Like: 
```js
'yml/file-extension': ['warn', {
  extension: 'yaml',
  caseSensitive: true,
  ignore: [
    '.gitlab-ci.yml',
    'dependabot.yml',

   // I'm not sure we have the full path in the code, 
   // but if - would be nice here
   /\.github/
  ]
}]
```

Can this be done? Do you need a PR?
Thanks :)

**Comment by ota-meshi** [comment]
Thank you for posting issue.

I think you can already make some files ignored.

```js
  "overrides": [
    {
      "files": [".gitlab-ci.yml", "dependabot.yml"],
      "rules": {
        "yml/file-extension": ["off"]
      }
    }
  ]
```

https://eslint.org/docs/latest/user-guide/configuring/configuration-files#how-do-overrides-work

So I don't think we need new options. What do you think?

**Comment by MorevM** [comment]
Yeah, I did exactly that for a couple of projects locally, but for some reason I didn't think about doing it once in a shared configuration.. Kinda brainlag, sorry for your time and attention to this. :) 

Although I still think this is may be a good option within the rule itself, this is not an issue anymore - `overrides` is a good option as well. 
Thank you for help and quick response, I close this.
