### ISSUE TITLE
Change dependency on `yaml-eslint-parser` to a peerDependency(?)

### ISSUE THREAD

**Issue by ericcornelissen** [ota-meshi/eslint-plugin-yml#198]
The dependency on [`yaml-eslint-parser` of this project](https://github.com/ota-meshi/eslint-plugin-yml/blob/9e1568a73a7272060a4b841e401fc4edd6e33f99/package.json#L60) came up while setting up [knip] (a tool to _"[find] unused files, dependencies and exports"_). In particular, this tool reports `yaml-eslint-parser` as an unlisted dependency[^1] when using the `eslint-plugin-yml`.

While tools such as [knip] are often imperfect, in this case I feel like there's some merit to the report - and I wonder if it would make sense for this project to change `yaml-eslint-parser` from a dependency to a peerDependency. On the one hand this might be awkward when using this plugin with the `"plugin:yml/standard"` extension, but on the other hand it seems sensible to me when explicitly specifying `parser: "yaml-eslint-parser"` for `.y{,a}ml` files.

I'm fine with whatever decision this project makes, I just wanted to pose the question.

[knip]: https://www.npmjs.com/package/knip

[^1]: A dependency that's present in the project being analyzed, but is not defined in `package.json`. Depending on modules not defined in `package.json` is, in general, a bad practice as transitive dependencies may be removed without notice (such as a major version bump).

**Comment by ota-meshi** [comment]
Thank you for posting issue.

However, I'm not sure what your problem is.
This plugin depends on the AST generated by yaml-eslint-parser.
So I think it should be a `dependency`. What makes you think `peerDependency` is better?

**Comment by ericcornelissen** [comment]
Thanks for your response and sharing your thoughts on the matter.

I tried to look into this further but can't come up with anything more concrete than what's mentioned in the footnote of the original issue:

> Depending on modules not defined in `package.json` is, in general, a bad practice as transitive dependencies may be removed without notice (such as a major version bump).

which, again, only applies if a user specify `parser: "yaml-eslint-parser"` in their ESLint configuration. Do note that in the scenario where the user installs an **incompatible** version of yaml-eslint-parser themselves, using a peerDependency relation would make it far easier to understand that there's an incompatibility (as npm will just tell you). 

However, since I lean towards your opinion on this topic, I'll close this issue.

**Comment by ota-meshi** [comment]
> Do note that in the scenario where the user installs an incompatible version of yaml-eslint-parser themselves

As you say, users should be aware of that, but it's not a big problem at this point. Because yaml-eslint-parser is not used outside of the packages I know of at the moment.
Parsers that are popular and used by many plugins like `@typescript-eslint/parser` might be better for users if they are defined in peerDependency.
