### ISSUE TITLE
Export yaml parser for ESLint flat config

### ISSUE THREAD

**Issue by danielrentz** [ota-meshi/eslint-plugin-yml#203]
Please add an export for the yaml parser used by the plugin, similar to the exports in [`eslint-plugin-jsonc`](https://github.com/ota-meshi/eslint-plugin-jsonc/blob/master/lib/index.ts).

This would allow to pass the plugin object directly to the [`parser` option of ESLint's new flat config](https://eslint.org/docs/latest/user-guide/configuring/configuration-files-new#configuring-a-custom-parser-and-its-options).

Example `eslint.config.js`:
```
import jsonPlugin from "eslint-plugin-jsonc";
import yamlPlugin from "eslint-plugin-yml";

export default [
  {
    files: ["**/*.json"],
    plugins: {
      jsonc: jsonPlugin
    },
    languageOptions: {
      parser: jsonPlugin // <================== works
    },
    rules: jsonPlugin.configs["recommended-with-json"].rules
  },
  {
    files: ["**/*.{yaml,yml}"],
    plugins: {
      yml: yamlPlugin
    },
    languageOptions: {
      parser: yamlPlugin // <================ does not work
    },
    rules: yamlPlugin.configs.recommended.rules
  }
}];
```

**Comment by ota-meshi** [comment]
I do not want to add a parsing method to eslint-plugin-yml. You can import from yaml-eslint-parser.
eslint-plugin-jsonc was not previously a separate parser package. It is for backward compatibility.

**Comment by danielrentz** [comment]
Agreed, will change my setup for jsonc accordingly, explicitly importing the parser.
