### ISSUE TITLE
add "no-unused-vars" to ignore list in base configuration

### ISSUE THREAD

**Issue by danielrentz** [ota-meshi/eslint-plugin-yml#204]
ESLint's recommended rule "no-unused-vars" triggers if a YAML comment starts with the word "global", because ESLint takes this as file-level definition of global symbols, which is useless in YAML.

```yaml
# global symbols
data: [my, global, symbols]
```

gives

```none
  1:11  error  'symbols' is defined but never used  no-unused-vars
```

Thus, this rule should go into the base config next to "no-irregular-whitespace" and "spaced-comment".

**Comment by ota-meshi** [comment]
I think it's fine to turn off no-unused-vars in the base config.
