### ISSUE TITLE
Ban Key/Variable names in YML files

### ISSUE THREAD

**Issue by Fab10-OpenTable** [ota-meshi/eslint-plugin-yml#210]
Can I use eslint-plugin-YML to validate YML files don't contain specific key/variable names?

**Comment by ota-meshi** [comment]
I think you can do it using eslint-plugin-json-schema-validator.
https://github.com/ota-meshi/eslint-plugin-json-schema-validator

[DEMO](https://ota-meshi.github.io/eslint-plugin-json-schema-validator/playground/#eJxtjkFuhDAMRa9ime0kSKOu2PUCvUDTRQADqYJNHTPTqurdO8CM1EXl1X/f3/7fOKRML3EmbNBTyYlNO/8V54wn7KTfeAWHAe9F2JVuojm6S8ypjyZas7jEu2zglVRFTxBwMltKU9dbxh+ZctsmLzrWj0cB3wJX4Bw8t7IayGJJuDTwSItFN1OZkh+TTWvrk9zDbsnrmNj930nXTOVPMz/ZnKv7+cD0acR9aQIDOHg63whfdtWqXAtpwAZMVwq8X9qtgPSxzeYFvEblgAcvpqmzg8swbBh/fgE9uHsQ)
