### ISSUE TITLE
Conflict with @typescript-eslint/parser 

### ISSUE THREAD

**Issue by dennismphil** [ota-meshi/eslint-plugin-yml#261]
Thank you for your hard work on this better YAML linter.

Reporting an error I saw while using this plugin along with `@typescript-eslint/parser`. Is it possible to provide an example how to use this with `@typescript-eslint/parser`?

### Error

`Error: Error while loading rule '@typescript-eslint/await-thenable': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
`

### Version

```js
// package.json
 ...
 "devDependencies": {
    "eslint": "^8.44.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-jsdoc": "^46.4.3",
    "eslint-plugin-svelte": "^2.33.0",
    "eslint-plugin-yml": "^1.8.0",
 }
```

### ESLint Config

```js
// .eslintrc.cjs
module.exports = {
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaVersion: 2020,
    sourceType: 'module',
    tsconfigRootDir: __dirname,
    project: ['./tsconfig.json', './tsconfig.eslint.json'],
    extraFileExtensions: ['.svelte'],
  },
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:@typescript-eslint/recommended-requiring-type-checking',
    'plugin:jsdoc/recommended',
    'plugin:svelte/recommended',
    'plugin:yml/standard',
  ],
  plugins: ['@typescript-eslint'],
  overrides: [
    ...
    {
      files: ['*.yaml', '*.yml'],
      parser: 'yaml-eslint-parser',
      parserOptions: {
        defaultYAMLVersion: '1.2',
      },
    },
};
```

### Detailed Error

```sh
[lint:js ] Oops! Something went wrong! :(
[lint:js ] 
[lint:js ] ESLint: 8.44.0
[lint:js ] 
[lint:js ] Error: Error while loading rule '@typescript-eslint/await-thenable': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
[lint:js ] Occurred while linting /specs/api.yaml
[lint:js ]     at Object.getParserServices (/node_modules/.pnpm/@typescript-eslint+utils@6.0.0_eslint@8.44.0_typescript@5.1.6/node_modules/@typescript-eslint/utils/dist/eslint-utils/getParserServices.js:18:15)
[lint:js ]     at create (/node_modules/.pnpm/@typescript-eslint+eslint-plugin@6.0.0_@typescript-eslint+parser@6.0.0_eslint@8.44.0_typescript@5.1.6/node_modules/@typescript-eslint/eslint-plugin/dist/rules/await-thenable.js:44:31)
[lint:js ]     at Object.create (/node_modules/.pnpm/@typescript-eslint+utils@6.0.0_eslint@8.44.0_typescript@5.1.6/node_modules/@typescript-eslint/utils/dist/eslint-utils/RuleCreator.js:38:20)
[lint:js ]     at createRuleListeners (/node_modules/.pnpm/eslint@8.44.0/node_modules/eslint/lib/linter/linter.js:870:21)
[lint:js ]     at /node_modules/.pnpm/eslint@8.44.0/node_modules/eslint/lib/linter/linter.js:1040:110
[lint:js ]     at Array.forEach (<anonymous>)
[lint:js ]     at runRules (/node_modules/.pnpm/eslint@8.44.0/node_modules/eslint/lib/linter/linter.js:977:34)
[lint:js ]     at Linter._verifyWithoutProcessors (/node_modules/.pnpm/eslint@8.44.0/node_modules/eslint/lib/linter/linter.js:1330:31)
[lint:js ]     at Linter._verifyWithConfigArray (/node_modules/.pnpm/eslint@8.44.0/node_modules/eslint/lib/linter/linter.js:1706:21)
[lint:js ]     at Linter.verify (/node_modules/.pnpm/eslint@8.44.0/node_modules/eslint/lib/linter/linter.js:1412:65)
[lint:js ]  ELIFECYCLE  Command failed with exit code 2.
[check   ]  ELIFECYCLE  Command failed.
ERROR: "lint:js" exited with 1.
```

**Comment by ota-meshi** [comment]
The rules that use their type information are not compatible with YAML files. Either turn those rules off in the YAML section in `overrides`, or add a section for using type information in `overrides` and use `'plugin:@typescript-eslint/recommended-requiring-type-checking'` there please.

**Comment by dblock** [comment]
Running into this problem and can't seem to fix it, probably noob.

https://github.com/dblock/opensearch-api-specification/commit/27c194a217c6b38c501618a87f4cc7eac28c99d2

I understand how to turn the typescript rules one-by-one, which will be a long list.

```yaml
rules: {
      '@typescript-eslint/dot-notation': 'off',
      '@typescript-eslint/no-implied-eval': 'off'
    }
```

But there has to be a better way?

**Comment by pfe-nazaries** [comment]
> **Update**: figured it out, [dblock/opensearch-api-specification@cbb7186](https://github.com/dblock/opensearch-api-specification/commit/cbb7186a9d4afa4205efe7bd34a53498f53f641b).
> 
> Running into this problem and can't seem to fix it, probably noob.
> 
> [dblock/opensearch-api-specification@27c194a](https://github.com/dblock/opensearch-api-specification/commit/27c194a217c6b38c501618a87f4cc7eac28c99d2)
> 
> I understand how to turn the typescript rules one-by-one, which will be a long list.
> 
> rules: {
>       '@typescript-eslint/dot-notation': 'off',
>       '@typescript-eslint/no-implied-eval': 'off'
>     }
> But there has to be a better way?

Is this the recommended approach to fix the issue?
