### ISSUE TITLE
Dependabot - Uncaught Exception in yaml

### ISSUE THREAD

**Issue by byrne-greg** [ota-meshi/eslint-plugin-yml#350]
![image](https://github.com/user-attachments/assets/7d028574-ede4-449e-8ff5-782671548edc)

This is coming through the package dependency on `yaml-eslint-parser`

<img width="439" alt="image" src="https://github.com/user-attachments/assets/353535c9-8b35-4f8a-a381-69b748db60d1">

**Comment by ota-meshi** [comment]
I think you can solve the problem by deleting the lock file and reinstalling.
