### ISSUE TITLE
conflict with ESLint rule `no-multi-spaces`

### ISSUE THREAD

**Issue by prazdevs** [ota-meshi/eslint-plugin-yml#89]
Hi, I ran into an issue having the rule `no-multi-spaces` enabled, as it parsed yaml indentation as unecessary spaces. When adding `--fix` it compltely destroys the yaml file.

Solution: turning off the `no-multi-spaces` rule in base overrides.

I will make a PR later ~~today~~. :)

**Comment by ota-meshi** [comment]
I couldn't reproduce the conflicting issue. Would you please share the YAML file and the config to reproduce?

**Comment by prazdevs** [comment]
here's my config:
https://github.com/prazdevs/eslint-config/blob/main/packages/javascript/index.js

and a yaml file i used from a project:
https://github.com/prazdevs/potato-timer/blob/main/locales/en.yml

The config already has the override
