### ISSUE TITLE
yml/flow-sequence-bracket-spacing always invalid option

### ISSUE THREAD

**Issue by leotm** [ota-meshi/eslint-plugin-yml#96]
Think we need to add at least _always_ option to get it linting then fixing, but the _error_ option works great by default

https://ota-meshi.github.io/eslint-plugin-yml/rules/flow-sequence-bracket-spacing.html#options

> - always # or "never"

https://eslint.org/docs/rules/array-bracket-spacing#options

> This rule has a string option:
> - "never" (default) disallows spaces inside array brackets
> - "always" requires one or more spaces or newlines inside array brackets

![Screenshot 2021-07-31 at 15 16 59](https://user-images.githubusercontent.com/1881059/127742672-c654fe89-1ef9-49b0-bf73-3772174a4fc9.png)

**Comment by ota-meshi** [comment]
You should read the eslint documentation.
https://eslint.org/docs/user-guide/configuring/rules#configuring-rules

**Comment by leotm** [comment]
Oops tried correct rule now `'yml/flow-sequence-bracket-spacing': ['error', 'always']`

The lint works

![Screenshot 2021-07-31 at 19 47 50](https://user-images.githubusercontent.com/1881059/127749781-5b13f4cf-fd01-4adb-a7c3-9f428b656dfd.png)

But after save/autofix lint's false positive

![Screenshot 2021-07-31 at 19 48 03](https://user-images.githubusercontent.com/1881059/127749785-8f5468d4-e6bc-403b-a8e8-0a55b7c0decd.png)

Then hitting save again reverts back to screen 1

**Comment by ota-meshi** [comment]
These rules conflict and cannot be used together.
If you want to use the `yml/flow-sequence-bracket-spacing` rule in YAML, don't use Prettier in YAML.
If you want to use Prettier in YAML, don't use the `yml/flow-sequence-bracket-spacing` rule in YAML.

If you want to use Prettier, you can use `plugin:yml/prettier` to turn off conflicting rules.
https://ota-meshi.github.io/eslint-plugin-yml/user-guide/#configuration

Put `plugin:yml/prettier` at the end of `"extends"` as well as eslint-config-prettier.
https://github.com/prettier/eslint-config-prettier

**Comment by leotm** [comment]
Thx, got it working perfectly

![Screenshot 2021-08-22 at 19 41 17](https://user-images.githubusercontent.com/1881059/130366330-8df70022-87eb-416c-b775-f4d5393bb0de.png)

* Made sure `esbenp.prettier-vscode` doesn't format _yaml_
* Removed `@react-native-community` and `plugin:prettier/recommended`

Removed `eslint-config-prettier` too since doesn't seem to affect `plugin:prettier/recommended` altho [recommended](https://github.com/prettier/eslint-plugin-prettier#recommended-configuration)

And removed `eslint-plugin-prettier` since not needed

I'll dig into the cause of `@react-native-community` and `plugin:prettier/recommended` interfering
